---
- hosts: agents
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:
    - name: install keylime and its dependencies
      tags: install_keylime,install_all
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: install package
      tags: install_swtpm,install_all
      dnf:
        name:
          - dbus
          - dbus-daemon
          - dbus-devel
          - swtpm-tools
          - swtpm
        state: latest
        update_cache: yes

    - name: copy swtpm starting script
      tags: install_swtpm,install_all
      copy:
        src: ./resources/swtpm.sh
        dest: /root/
        owner: root
        group: root
        mode: 0755

    - name: configure registrar ip
      tags: keylime_agent_conf,install_all
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^cloudagent_ip = *'
        line: cloudagent_ip = 0.0.0.0

    - name: configure registrar ip
      tags: keylime_agent_conf,install_all
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^registrar_ip = *'
        line: registrar_ip = {{ registrar_ip }}

    - name: configure agent uuid
      tags: keylime_agent_conf,install_all
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^agent_uuid = *'
        line: agent_uuid = hostname

    - name: configure tpm ek to false
      tags: keylime_agent_conf,install_all
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^require_ek_cert = *'
        line: require_ek_cert = False

    - name: start service swtpm
      tags: start_swtpm,start_dependencies
      shell: /root/swtpm.sh
      async: 2592000
      poll: 0

    - name: start service keylime agent
      tags: start_agent
      shell: /usr/bin/keylime_agent
      async: 2592000
      poll: 0

    - name: start service keylime ima emulator
      tags: start_ima_emulator,start_dependencies
      shell: /usr/bin/keylime_ima_emulator
      async: 2592000
      poll: 0

    - name: stop swtpm, tpm2-abrmd, and keylime_agent
      tags: stop_all
      shell: killall keylime_agent swtpm tpm2-abrmd --wait
      ignore_errors: true

    - name: uninstall agent
      tags: uninstall
      dnf:
        name: keylime
        state: absent

    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent

    - name: remove swtpm.sh
      tags: uninstall
      file:
        path: /root/swtpm.sh
        state: absent
