--- 
- hosts: registrar
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:

    - name: install keylime and its dependencies
      tags: install
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: disable tls
      tags: config
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: 'enable_tls = *'
        line: enable_tls = False

    - name: set registrar's verifier ip
      tags: config
      replace:
        path: /etc/keylime.conf
        regexp: '^cloudverifier_ip = .*'
        replace: cloudverifier_ip = {{ verifier_ip }}

    - name: set registrar's registrar ip
      tags: config
      replace:
        path: /etc/keylime.conf
        regexp: '^registrar_ip = .*'
        replace: registrar_ip = 0.0.0.0

    - name: comment out 1st of  3 lines in registrar_client.py
      tags: config
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/registrar_client.py
        firstmatch: yes
        regexp: '^\s*if not tls_enabled:'
        line: '    # if not tls_enabled:'

    - name: comment out 2nd of  3 lines in registrar_client.py
      tags: config
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/registrar_client.py
        firstmatch: yes
        regexp: '^\s*raise Exception\('
        line: '    #     raise Exception('

    - name: comment out 3rd of  3 lines in registrar_client.py
      tags: config
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/registrar_client.py
        firstmatch: yes
        regexp: '^\s*\"It is unsafe to use this interface to query AIKs without server-authenticated TLS.\"\)'
        line: '    #         "It is unsafe to use this interface to query AIKs without server-authenticated TLS.")'

    - name: before starting keylime verifier, start verifier first to generate log file
      tags: run_verifier
      command: keylime_verifier
      async: 30000
      poll: 0

    - name: kill verifier
      tags: kill_verifier
      shell: killall keylime_verifier --wait
      async: 30000
      poll: 0

    - name: close service firewall
      tags: start
      service:
        name: firewalld
        state: stopped

    - name: start registrar
      tags: start
      command: keylime_registrar
      async: 36000
      poll: 0

    - name: stop registrar
      tags: stop
      shell: killall keylime_registrar --wait
      ignore_errors: true

    - name: uninstall registrar
      tags: uninstall
      dnf:
        name: keylime
        state: absent
  
    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent
