---
- hosts: webapp
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:
    - name: install keylime and its dependencies
      tags: install
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: before start keylime webapp, start verifier first to generate certificates in /var/lib/keylime/cv_ca
      tags: run_verifier
      shell: keylime_verifier
      async: 300
      poll: 0

    - name: kill verifier
      tags: kill_verifier
      shell: killall keylime_verifier --wait

    - name: copy static file to /usr/lib/python3.9/site-packages/keylime
      tags: config_webapp
      copy:
        src: ./resources/{{ item }}
        dest: /usr/lib/python3.9/site-packages/keylime/
        owner: root
        group: root
        mode: 0644
      with_items:
        - static.tar.gz

    - name: unzip static.tar.gz
      tags: config_webapp
      shell: tar -xzvf /usr/lib/python3.9/site-packages/keylime/static.tar.gz -C /usr/lib/python3.9/site-packages/keylime/

    - name: fix tenant_webapp.py
      tags: config_webapp
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/tenant_webapp.py
        firstmatch: yes
        regexp: 'my_tls_cert = *'
        line: '    my_tls_cert = "%s" % (my_cert)'

    - name: fix tenant_webapp.py
      tags: config_webapp
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/tenant_webapp.py
        firstmatch: yes
        regexp: 'my_tls_priv_key = *'
        line: '    my_tls_priv_key = "%s" % (my_priv_key)'

    - name: disable tls
      tags: disable_tls,config_webapp
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: 'enable_tls = *'
        line: enable_tls = False

    - name: set verifier ip
      tags: config_webapp
      replace:
        path: /etc/keylime.conf
        regexp: '^cloudverifier_ip = .*'
        replace: cloudverifier_ip = {{ verifier_ip }}

    - name: set registrar ip
      tags: config_webapp
      replace:
        path: /etc/keylime.conf
        regexp: '^registrar_ip = .*'
        replace: registrar_ip = {{ registrar_ip }}

    - name: configure tpm ek to false
      tags: config_webapp
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^require_ek_cert = *'
        line: require_ek_cert = False
    
    - name: start keylime webapp
      tags: start_webapp
      shell: /usr/bin/keylime_webapp
      async: 2592000
      poll: 0

    - name: stop webapp
      tags: stop
      shell: killall keylime_webapp --wait
      ignore_errors: true

    - name: uninstall webapp
      tags: uninstall
      dnf:
        name: keylime
        state: absent

    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent

    - name: remove static resource
      tags: uninstall
      file:
        path: /usr/lib/python3.9/site-packages/keylime/{{ item }}
        state: absent
      with_items:
        - static
        - static.tar.gz
