--- 
- hosts: verifier
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:

    - name: install keylime and its dependencies
      tags: install_keylime,start_with_installation
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: distable tls 
      tags: disable_tls,start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: 'enable_tls = *'
        line: enable_tls = False
    
    - name: set registrar's ip
      tags: configure_registrar_ip,start,start_with_installation
      replace:
        path: /etc/keylime.conf
        regexp: '^registrar_ip = .*'
        replace: registrar_ip = {{ registrar_ip }}

    - name: set verifier ip to 0.0.0.0
      tags: configure_verifier_ip,start,start_with_installation
      replace:
        path: /etc/keylime.conf
        regexp: '^cloudverifier_ip = .*'
        replace: cloudverifier_ip = 0.0.0.0

    - name: close service firewall
      tags: close_firewall,start,start_with_installation
      service:
        name: firewalld
        state: stopped

    - name: start verifier
      tags: start_alone,start,start_with_installation
      command: keylime_verifier
      async: 36000
      poll: 0

    - name: stop verifier
      tags: stop
      shell: killall keylime_verifier --wait
      ignore_errors: true

    - name: uninstall verifier
      tags: uninstall
      dnf:
        name: keylime
        state: absent
  
    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent
