--- 
- hosts: agents 
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:

    - name: install keylime and its dependencies
      tags: install_keylime,start_with_installation
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: install package
      tags: install_swtpm,start_with_installation
      dnf:
        name:
          - dbus
          - dbus-daemon
          - dbus-devel
          - swtpm-tools
          - swtpm
        state: latest
        update_cache: yes

    - name: copy swtpm starting script
      tags: start,start_with_installation
      copy:
        src: ./resources/{{ item }}
        dest: /root/
        owner: root
        group: root
        mode: 0755
      with_items:
        - swtpm.sh
        - keylime-agent.sh

    - name: configure registrar ip
      tags: start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^cloudagent_ip = *'
        line: cloudagent_ip = 0.0.0.0

    - name: configure registrar ip
      tags: start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^registrar_ip = *'
        line: registrar_ip = {{ registrar_ip }}

    - name: configure agent uuid
      tags: configure_uuid,start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^agent_uuid = *'
        line: agent_uuid = {{ inventory_hostname }}

    - name: configure tpm ek to false
      tags: disable_ek,start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^require_ek_cert = *'
        line: require_ek_cert = False

    - name: start service swtpm
      tags: start,start_with_installation
      shell: 
        cmd: bash /root/swtpm.sh
      async: 36000
      poll: 0

    - name: start service keylime agent
      tags: start,start_with_installation
      shell:
        cmd: bash /root/keylime-agent.sh
      async: 36000
      poll: 0

    - name: start service keylime ima emulator
      tags: start,start_with_installation
      command: keylime_ima_emulator
      async: 36000
      poll: 0

    - name: stop swtpm, tpm2-abrmd, and keylime_agent
      tags: stop
      shell: killall keylime_agent swtpm tpm2-abrmd --wait
      ignore_errors: true

    - name: uninstall agent
      tags: uninstall
      dnf:
        name: keylime
        state: absent

    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent

    - name: remove swtpm.sh, keylime-agent.sh
      tags: uninstall
      file:
        path: /root/{{ item }}      
        state: absent
      with_items:
        - swtpm.sh
        - keylime-agent.sh
