--- 
- hosts: agents 
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:

    - name: install keylime and its dependencies
      tags: install_keylime_on_agents,install_keylime
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: install package
      tags: install_packages,start_agent
      dnf:
        name:
          - dbus
          - dbus-daemon
          - dbus-devel
          - swtpm-tools
          - swtpm
        state: latest
        update_cache: yes

    - name: copy swtpm starting script
      tags: copy_file,start_agent
      copy:
        src: ./resources/{{ item }}
        dest: /root/
        owner: root
        group: root
        mode: 0755
      with_items:
        - swtpm.sh
        - keylime-agent.sh

    - name: configure registrar ip
      tags: configure_agent,start_agent
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^cloudagent_ip = *'
        line: cloudagent_ip = 0.0.0.0

    - name: configure registrar ip
      tags: configure_registrar,start_agent
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^registrar_ip = *'
        line: registrar_ip = {{ registrar_ip }}

    - name: configure agent uuid
      tags: configure_uuid,start_agent
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^agent_uuid = *'
        line: agent_uuid = {{ uuid }}

    - name: configure tpm ek to false
      tags: configure_tpm_ek,start_agent
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: '^require_ek_cert = *'
        line: require_ek_cert = False

    - name: start service swtpm
      tags: start_service,start_swtpm,start_agent
      shell: 
        cmd: bash /root/swtpm.sh
      async: 36000
      poll: 0

    - name: start service keylime agent
      tags: start_service,start_keylime_agent,start_agent
      shell:
        cmd: bash /root/keylime-agent.sh
      async: 36000
      poll: 0

    - name: start service keylime ima emulator
      tags: start_service,start_keylime_ima,start_agent
      command: keylime_ima_emulator
      async: 36000
      poll: 0

    - name: stop swtpm, tpm2-abrmd, and keylime_agent
      tags: agents_stop_all
      shell: killall keylime_agent swtpm tpm2-abrmd --wait
      ignore_errors: true

