--- 
- hosts: webapp 
  become: yes
  vars_files:
    - ./vars/ips.yml
  tasks:

    - name: install keylime and its dependencies 
      tags: install_keylime,start_with_installation
      dnf:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - keylime
        - wget
        - gcc
        - make
        - openssl-devel
        - vim
        - iputils
        - lsof

    - name: copy static file to /usr/lib/python3.9/site-packages/keylime 
      tags: start,start_with_installation
      copy:
        src: ./resources/{{ item }}
        dest: /usr/lib/python3.9/site-packages/keylime/
        owner: root
        group: root
        mode: 0644
      with_items:
        - static.tar.gz

    - name: unzip static.tar.gz
      tags: start,start_with_installation
      command: tar -xzvf /usr/lib/python3.9/site-packages/keylime/static.tar.gz -C /usr/lib/python3.9/site-packages/keylime/

    - name: fix tenant_webapp.py
      tags: start,start_with_installation
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/tenant_webapp.py
        firstmatch: yes
        regexp: 'my_tls_cert = *'
        line: '    my_tls_cert = "%s" % (my_cert)'

    - name: fix tenant_webapp.py
      tags: start,start_with_installation
      lineinfile:
        path: /usr/lib/python3.9/site-packages/keylime/tenant_webapp.py
        firstmatch: yes
        regexp: 'my_tls_priv_key = *'
        line: '    my_tls_priv_key = "%s" % (my_priv_key)'

    - name: disable tls
      tags: disable_tls,start,start_with_installation
      lineinfile:
        path: /etc/keylime.conf
        firstmatch: yes
        regexp: 'enable_tls = *'
        line: enable_tls = False

    - name: set verifier ip
      tags: start,start_with_installation
      replace:
        path: /etc/keylime.conf
        regexp: '^cloudverifier_ip = .*'
        replace: cloudverifier_ip = {{ verifier_ip }}

    - name: set registrar ip
      tags: start,start_with_installation
      replace:
        path: /etc/keylime.conf
        regexp: '^registrar_ip = .*'
        replace: registrar_ip = {{ registrar_ip }}

    - name: before start keylime webapp, start verifier & registrar first to generate log file
      tags: start,start_with_installation
      command: keylime_verifier
      async: 30000
      poll: 0

    - name: before start keylime webapp, start verifier & registrar first to generate log file
      tags: start,start_with_installation
      command: keylime_registrar
      async: 30000
      poll: 0

    - name: kill verifier & registrar
      tags: start,start_with_installation
      shell: killall keylime_verifier keylime_registrar --wait
      async: 30000
      poll: 0

    - name: close service firewall
      tags: close_firewall,start,start_with_installation
      service:
        name: firewalld
        state: stopped

    - name: start keylime webapp
      tags: start_alone,start,start_with_installation
      command: keylime_webapp
      async: 36000
      poll: 0

    - name: stop webapp
      tags: stop
      shell: killall keylime_webapp --wait
      ignore_errors: true

    - name: uninstall webapp
      tags: uninstall
      dnf:
        name: keylime
        state: absent
  
    - name: remove log folder
      tags: uninstall
      file:
        path: /var/log/keylime/
        state: absent

    - name: remove static resource
      tags: uninstall
      file:
        path: /usr/lib/python3.9/site-packages/keylime/{{ item }}
        state: absent
      with_items:
        - static
        - static.tar.gz
